### ISSUE TITLE
Export to csv doesn't work

### ISSUE THREAD

**Issue by ppoektos** [arkhitech/redmine_timesheet_plugin#39]

**Comment by nkgokul** [comment]
Looks like you have used the default selection which is all projects, users etc. This results in a URI that is almost 10k characters long. I think it would be better to use POST for that so that URI character limit is not a problem. 

In the mean time you can use limited projects to to make sure that the URI generated is not long enough.

**Comment by astehlik** [comment]
I had the same problem with a ruby 2.5 installation.

It seems that the encoding parameter passed to the CSV generation method is not valid any more.

Please checkout my pull request which fixes the problem for me.
